### ISSUE TITLE
Some Issues with TickEvent

### ISSUE THREAD

**Issue by iceBear67** [hanbings/alkaid#4]
With alkaid, developers can handle ticks as some events, which is a good practice in some scenarios  

However, There're some issues with `TickEvent` (and its implementation):
 1. TickEvent.tick is always `1`
 
https://github.com/hanbings/alkaid/blob/d173945101714597a4594079ccb5639c973a2bca/alkaid-bukkit/src/main/java/com/alkaidmc/alkaid/bukkit/extra/AlkaidExtra.java#L39

 https://github.com/hanbings/alkaid/blob/d173945101714597a4594079ccb5639c973a2bca/alkaid-bukkit/src/main/java/com/alkaidmc/alkaid/bukkit/extra/event/TickEvent.java#L12

2. It sends tons of events even unused, which stresses GC

**Comment by hanbings** [comment]
Please check out the new commit. 
[commit 6301953] (https://github.com/hanbings/alkaid/commit/6301953d867ab05332c680f251e854a8ea88b0eb)
I've changed AtomicLong to static because Alkaid will detect duplicate loads and I believe this change will work. Thanks!

**Comment by iceBear67** [comment]
Just close this issue with your confidence.

**Comment by iceBear67** [comment]
There're still some issues with your new commit.

`TickEvent`, which should be immutable, varies its `tick` when a newer one is fired, breaking its immutability. (And it should be immutable.)

Once `TickEvent` is immutable(or not), an AtomicLong is no longer necessary. Also, events are fired on the Main Thread where you can confidently avoid thread-safe issues, you don't have to use such a wrapper.

Additionally, You'd better use methods like `getAndIncrease` that guarantee thread-safe(CAS inside) instead of `tick + 1`.

**Comment by hanbings** [comment]
New commit: https://github.com/hanbings/alkaid/commit/8368a3f6b768041b83f4f780ba2cfca8a00d66cc
In this commit (and the first two of this) we separated the Event from the Tick / Second counter so that the tick / second inside the Event is no longer mutable.
The problem has been fixed, thanks again!
