### ISSUE TITLE
Issues with SecondEvent

### ISSUE THREAD

**Issue by iceBear67** [hanbings/alkaid#5]
https://github.com/hanbings/alkaid/blob/d173945101714597a4594079ccb5639c973a2bca/alkaid-bukkit/src/main/java/com/alkaidmc/alkaid/bukkit/extra/event/SecondEvent.java#L17

It's supposed to be the time when the object created

Also, A Javadoc comment is necessary because it's an async event (You're using java.util.Timer for implementation)

**Comment by hanbings** [comment]
It looks like this issue has been resolved in a previous commit (https://github.com/hanbings/alkaid/issues/4 and https://github.com/hanbings/alkaid/commit/6301953d867ab05332c680f251e854a8ea88b0eb). Thanks for your contribution!
