### ISSUE TITLE
DependManagerFactory is broken..

### ISSUE THREAD

**Issue by iceBear67** [hanbings/alkaid#6]
https://github.com/hanbings/alkaid/blob/d173945101714597a4594079ccb5639c973a2bca/alkaid-bukkit/src/main/java/com/alkaidmc/alkaid/bukkit/server/DependManager.java#L76

Why can't I get the plugin from `getPlugin` directly while the class is present?

**Comment by milkory** [comment]
Do you mean we can simplify L69?

**Comment by milkory** [comment]
Otherwise, the class is not redundant as you can get the required class with a stream.

**Comment by iceBear67** [comment]
It is impossible for the plugin isn't loaded by the server while one of the targeted plugins' class is present, 

Can you provide me a scenario using this class? with your codes.

**Comment by iceBear67** [comment]
> Otherwise, the class is not redundant as you can get the required class with a stream.

So there is no reason to have such a failure handler, even the class.

What do you mean "with stream"? It can be done by a simple null check or Optional, like what had been done in MythicMobs

**Comment by milkory** [comment]
I've understood what you mean.

**Comment by hanbings** [comment]
We're about to do a full refactoring that we believe will fix the problem. Thanks for your contribution!
